services:
  - type: web
    name: sistema-votacion
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///database/votacion.db
      - key: PYTHON_VERSION
        value: 3.11.11
    disk:
      name: data
      mountPath: /app/database
      sizeGB: 1